### ISSUE TITLE
Create AWS AMI image for ScaleIO

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#136]
Target date 05/13/2016

- Create AMIs that spin up ScaleIO 3-node cluster on CentOS

**Comment by mux23** [comment]
ScaleIO 2.0.0 up and running successfully on AWS. Current challenge: when AMIs come up there is no way to predict their IP addresses, and as such no way to build the cluster without (pretty serious) human interaction. Experimenting now with using a defined VPC network and assigning the IP addresses automatically.

**Comment by mux23** [comment]
still fighting with AWS networking - found (and reported) a bug with Cloudformation Designer, wherein adding a rule allowing all instances in a VPC unrestricted access to each other resulted in a circular dependancy, alleviated by using AWS::EC2::SecurityGroupIngress instead of AWS::EC2::SecurityGroup... but then AWS::EC2::SecurityGroupIngress isn't supported by Cloudformation Designer, for no reason at all. hacked around it with static rules. cluster is working, but ScaleIO isn't quite yet.

**Comment by mux23** [comment]
this is now complete, and the Cloudformation templates are available at https://github.com/mux23/aws-scaleio

This project actually ended up being _three_ AMI images, a VPC and subnet, some routing logic and assorted plumbing. Works well, as far as I can tell - we'll se when we try to put it into action.
