### ISSUE TITLE
Show different cloud formation templates for deploying

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#32]

**Comment by drumulonimbus** [comment]
a preliminary template is now being worked on at https://github.com/drumulonimbus/rexray-cf/

**Comment by drumulonimbus** [comment]
template is launching, but something in the build stage is failing and the template automatically rolls back (ie, shuts down and deletes the instance). currently working on cause analysis.

also working on basic documentation for the readme.md

**Comment by drumulonimbus** [comment]
current status - template launches, Docker and rexray install and start successfully. Working on passing the user's AWS credentials to rexray - currently attempting to have Cloudformation spawn a new set of IAM creds just for rexray, and it feels like it's *almost* working - going to push at it for another hour or two, but if I can't get it to work I'll just have the user pass the access_key and secret_key in using user-data or commandline parameters. On track to have this working by the end of today.

**Comment by clintonskitson** [comment]
Very cool

**Comment by drumulonimbus** [comment]
the template now works - the IAM user is created successfully, the auth keys are generated and (*finally*) the config files are populating with the access and secret keys... but currently, rexray fails due to an authentication error, not sure why. I suspect it has to do with AWS IAM user policies, and that I'll need to explicitly grant the temporary 'RexrayUser' user access to read/create/delete EC2 EBS volumes, though my first attempts at this haven't proven fruitful.

a log of the ongoing work is here: https://github.com/drumulonimbus/rexray-cfn/commits/master

**Comment by drumulonimbus** [comment]
prototyping was long since completed, should have updated this a while back.
