### ISSUE TITLE
Finalize cloud formation template

### ISSUE THREAD

**Issue by clintonskitson** [emccode/roadmap#33]

**Comment by drumulonimbus** [comment]
*thought* this was finalized - was well into the documentation portion before finding a bug that kinda set me back a bunch... turns out the Docker 'experimental' install script has a bug wherein Amazon Linux does not install the experimental version, and so Docker on Amazon Linux does not support the 'volume-driver' plugin. I spent some time trying to hack around this, but in the end it seems that it won't be trivial to get the experimental version installed on amzn Linux, and have been working to migrate my template over to use Ubuntu (or more specifically, to get the AWS cloud-init stuff working properly and installing software on Ubuntu).

**Comment by clintonskitson** [comment]
@drumulonimbus When this kind of thing happens, make an issue out of it and ask for help!

I would assume that you could get around the following steps 1) doing the Docker install as you did 2) download the docker experimental binary directly and replace existing 3) restart docker services.  The step #1 would just prep a system for Docker.

Also, the Docker volume driver functionality is not experimental anymore.  In Docker 1.8, it is in the normal binary.  The features for allowing someone to specify options or the `docker volume create` sub commands are in the experimental branch now.

**Comment by drumulonimbus** [comment]
I actually did reach out to Jessie Frazelle at Twitter to ask about the bug, and she pointed me to the installer script at https://github.com/docker/docker/blob/master/hack/install.sh - started to try to fix it, but in the end the problem is more that Docker isn't building 'experimental' packages for Amazon Linux.

I continually get a "flag provided but not defined" error from Docker, even with version 1.8:

'[root@ip-172-31-11-11 ~]# docker -v
Docker version 1.8.0-dev, build a031b64

[root@ip-172-31-11-11 ~]# docker run --volume-driver=rexray -v testing123:/foo centos
flag provided but not defined: --volume-driver
See 'docker run --help'.
[root@ip-172-31-11-11 ~]#'

**Comment by clintonskitson** [comment]
The version being used is a `-dev` build.  It might have been introduced prior to the VD functionality being moved from experimental.

**Comment by drumulonimbus** [comment]
complete overhaul completed a couple of days ago - template now uses Ubuntu 14.04LTS as the base, and has been tested a bunch and works exactly as expected.
